name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3

      - uses: aiken-lang/setup-aiken@v0.1.0
        with:
          version: v1.0.11-alpha

      - run: aiken fmt --check